export default {
  USER_RUNNING_CONTRACTS_SCREEN: "USER_RUNNING_CONTRACTS",
  USER_CONTRACTS_SCREEN: "USER_CONTRACTS",
  USER_CONTRACTS_HISTORY_SCREEN: "USER_CONTRACTS_HISTORY_SCREEN",
  TRANS_CONTRACTS_HISTORY_SCREEN: "TRANS_CONTRACTS_HISTORY_SCREEN",
  TRANS_CONTRACTS_SCREEN: "TRANS_CONTRACTS_SCREEN",
};
