export const vehInitFormState = {
  inputValues: {
    vtypid: "",
    vtypnm: "",
    vehno: "",
    vehregdte: "",
    vehinsexpdte: "",
    vehinsuno: "",
    vehchesino: "",
    vehphoto: [],
    vehregfle: "",
    vehinsurancedoc: "",
    vehfitcetexpdte: "",
    vehfitcetphoto: "",
    vehpucexpdte: "",
    vehpucphoto: "",
  },
  inputValidities: {
    vtypid: false,
    vtypnm: false,
    vehno: false,
    vehregdte: false,
    vehinsexpdte: false,
    vehinsuno: false,
    vehchesino: false,
    vehphoto: false,
    vehregfle: false,
    vehinsurancedoc: false,
    vehfitcetexpdte: false,
    vehfitcetphoto: false,
    vehpucexpdte: true,
    vehpucphoto: true,
  },
  formIsValid: false,
};
