import React from "react";
import { View, StyleSheet, Dimensions, ScrollView, Text } from "react-native";

import BackgroundImage from "../../shared/UI/BackgroundImage";

const window = Dimensions.get("window");

const TAndCModalScreen = (props) => {
  return (
    <BackgroundImage>
      <View style={styles.container}>
        <Text style={styles.heading}>Terms and Conditions</Text>
        <ScrollView>
          <Text style={styles.content}>INDIA</Text>
          <Text style={styles.content}>
            This Terms & Conditions forms an electronic record in terms of
            Information Technology Act, 2000 and amendments thereof. The same is
            generated by a computer system and does not require any physical or
            digital signature.
          </Text>
          <Text style={styles.content}>1. Contractual Relationship</Text>
          <Text style={styles.content}>
            These Terms of Use (“Terms”) govern the access or use by you, an
            individual, of applications, websites, content, products, and
            services (the “Services”) made available by SPRASH Technologies
            Private Limited (“T-port”) a private limited liability company
            established in India , having its registered office at SPARSH
            Technologies, RAJAT SANKUL Opp. S.T. Stand,Ganeshpeth Colony,
            Nagpur, Maharashtra. PLEASE READ THESE TERMS CAREFULLY BEFORE
            ACCESSING OR USING THE SERVICES. Your access and use of the Services
            constitutes your agreement to be bound by these Terms, which
            establishes a contractual relationship between you and SparshTech.
            If you do not agree to these Terms, you may not access or use the
            Services. These Terms expressly supersede prior agreements or
            arrangements with you. SparshTech may immediately terminate these
            Terms or any Services with respect to you, or generally cease
            offering or deny access to the Services or any portion thereof, at
            any time for any reason. Supplemental terms may apply to certain
            Services, such as policies for a particular event, activity or
            promotion, and such supplemental terms will be disclosed to you in
            connection with the applicable Services. Supplemental terms are in
            addition to, and shall be deemed a part of, the Terms for the
            purposes of the applicable Services. Supplemental terms shall
            prevail over these Terms in the event of a conflict with respect to
            the applicable Services. SparshTech may amend the Terms related to
            the Services from time to time. Amendments will be effective upon
            Tport's posting of such updated Terms at this location or the
            amended policies or supplemental terms on the applicable Service.
            Your continued access or use of the Services after such posting
            constitutes your consent to be bound by the Terms, as amended. Our
            collection and use of personal information in connection with the
            Services is as provided in T-port's Privacy Policy located at
            https://www.Tport.in/privacy/notice. SparshTech may provide to a
            claims processor or an insurer any necessary information (including
            your contact information) if there is a complaint, dispute or
            conflict, which may include an accident, involving you and a Third
            Party Provider (including a transportation network company driver)
            and such information or data is necessary to resolve the complaint,
            dispute or conflict.
          </Text>
          <Text style={styles.content}>2. The Services</Text>
          <Text style={styles.content}>
            The Services constitute a technology platform that enables users of
            T-port’s mobile applications or websites provided as part of the
            Services (each, an “Application”) to arrange and schedule
            transportation and/or logistics services with independent third
            party providers of such services, including independent third party
            transportation providers and independent third party logistics
            providers under agreement with SparshTech or certain of T-port’s
            affiliates (“Third Party Providers”). Unless otherwise agreed by
            T-port in a separate written agreement with you, the Services are
            made available solely for your personal, noncommercial use. YOU
            ACKNOWLEDGE THAT T_PORT DOES NOT PROVIDE TRANSPORTATION OR LOGISTICS
            SERVICES OR FUNCTION AS A TRANSPORTATION CARRIER AND THAT ALL SUCH
            TRANSPORTATION OR LOGISTICS SERVICES ARE PROVIDED BY INDEPENDENT
            THIRD PARTY CONTRACTORS WHO ARE NOT EMPLOYED BY TPORT OR ANY OF ITS
            AFFILIATES.
          </Text>
          <Text style={styles.content}>LICENSE.</Text>
          <Text style={styles.content}>
            Subject to your compliance with these Terms, Tport grants you a
            limited, non-exclusive, non-sublicensable, revocable,
            non-transferable license to: (i) access and use the Applications on
            your personal device solely in connection with your use of the
            Services; and (ii) access and use any content, information and
            related materials that may be made available through the Services,
            in each case solely for your personal, noncommercial use. Any rights
            not expressly granted herein are reserved by Tport and Tport’s
            licensors.
          </Text>
          <Text style={styles.content}>RESTRICTIONS.</Text>
          <Text style={styles.content}>You may not:</Text>
          <Text style={{ ...styles.subContent, marginTop: 5 }}>
            (i) Remove any copyright, trademark or other proprietary notices
            from any portion of the Services.
          </Text>
          <Text style={styles.subContent}>
            (ii) Reproduce, modify, prepare derivative works based upon,
            distribute, license, lease, sell, resell, transfer, publicly
            display, publicly perform, transmit, stream, broadcast or otherwise
            exploit the Services except as expressly permitted by Tport.
          </Text>
          <Text style={styles.subContent}>
            (iii) Decompile, reverse engineer or disassemble the Services except
            as may be permitted by applicable law.
          </Text>
          <Text style={styles.subContent}>
            (iv) Link to, mirror or frame any portion of the Services; (v) cause
            or launch any programs or scripts for the purpose of scraping,
            indexing, surveying, or otherwise data mining any portion of the
            Services or unduly burdening or hindering the operation and/or
            functionality of any aspect of the Services.
          </Text>
          <Text style={styles.subContent}>or</Text>
          <Text style={styles.subContent}>
            (vi) Attempt to gain unauthorized access to or impair any aspect of
            the Services or its related systems or networks.
          </Text>
          <Text style={{ ...styles.content, marginTop: 10 }}>
            PROVISION OF THE SERVICES.
          </Text>
          <Text style={styles.content}>
            You acknowledge that portions of the Services may be made available
            under Tport's various brands or request options associated with
            transportation or logistics, including the transportation request
            brands currently referred to as “Tport,” the logistic. You also
            acknowledge that the Services may be made available under such
            brands or request options by or in connection with: (i) certain of
            Tport’s subsidiaries and affiliates; or (ii) independent Third Party
            Providers, including transportation network company drivers,
            transportation charter permit holders or holders of similar
            transportation permits, authorizations or licenses.
          </Text>
          <Text style={styles.content}>THIRD PARTY SERVICES AND CONTENT.</Text>
          <Text style={styles.content}>
            The Services may be made available or accessed in connection with
            third party services and content (including advertising) that Tport
            does not control. You acknowledge that different terms of use and
            privacy policies may apply to your use of such third party services
            and content. Tport does not endorse such third party services and
            content and in no event shall Tport be responsible or liable for any
            products or services of such third party providers. Additionally,
            Apple Inc., Google, Inc., Microsoft Corporation and/or their
            applicable subsidiaries and affiliates will be third-party
            beneficiaries to this contract if you access the Services using
            Applications developed for Apple iOS, Android, or Microsoft Windows
            respectively. These third party beneficiaries are not parties to
            this contract and are not responsible for the provision or support
            of the Services in any manner. Your access to the Services using
            these devices is subject to terms set forth in the applicable third
            party beneficiary’s terms of service. OWNERSHIP. The Services and
            all rights therein are and shall remain Tport’s property or the
            property of Tport’s licensors. Neither these Terms nor your use of
            the Services convey or grant to you any rights: (i) in or related to
            the Services except for the limited license granted above; or (ii)
            to use or reference in any manner Tport’s company names, logos,
            product and service names, trademarks or services marks or those of
            Tport’s licensors.
          </Text>
          <Text style={styles.content}>3. Your Use of the Services</Text>
          <Text style={styles.content}>USER ACCOUNTS.</Text>
          <Text style={styles.content}>
            In order to use most aspects of the Services, you must register for
            and maintain an active personal user Services account (“Account”).
            You must be at least 18 years of age, or the age of legal majority
            in your jurisdiction (if different than 18), to obtain an Account.
            Account registration requires you to submit to Tport certain
            personal information, such as your name, address, mobile phone
            number and age, as well as at least one valid payment method (either
            a credit card or accepted payment partner). You agree to maintain
            accurate, complete, and up-to-date information in your Account. Your
            failure to maintain accurate, complete, and up-to-date Account
            information, including having an invalid or expired payment method
            on file, may result in your inability to access and use the Services
            or Tport’s termination of these Terms with you. You are responsible
            for all activity that occurs under your Account, and you agree to
            maintain the security and secrecy of your Account username and
            password at all times. Unless otherwise permitted by Tport in
            writing, you may only possess one Account.
          </Text>
          <Text style={styles.content}>USER REQUIREMENTS AND CONDUCT.</Text>
          <Text style={styles.content}>
            The Service is not available for use by persons under the age of 18.
            You may not authorize third parties to use your Account, and you may
            not allow persons under the age of 18 to receive transportation or
            logistics services from Third Party Providers unless they are
            accompanied by you. You may not assign or otherwise transfer your
            Account to any other person or entity. You agree to comply with all
            applicable laws when using the Services, and you may only use the
            Services for lawful purposes (e.g., no transport of unlawful or
            hazardous materials). You will not, in your use of the Services,
            cause nuisance, annoyance, inconvenience, or property damage,
            whether to the Third Party Provider or any other party. In certain
            instances you may be asked to provide proof of identity to access or
            use the Services, and you agree that you may be denied access to or
            use of the Services if you refuse to provide proof of identity.
          </Text>
          <Text style={styles.content}>TEXT MESSAGING.</Text>
          <Text style={styles.content}>
            By creating an Account, you agree that the Services may send you
            informational text (SMS) messages as part of the normal business
            operation of your use of the Services. You may opt-out of receiving
            text (SMS) messages from Tport at any time by sending an email to
            (info@sparshtech.com) indicating that you no longer wish to receive
            such messages, along with the phone number of the mobile device
            receiving the messages. You acknowledge that opting out of receiving
            text (SMS) messages may impact your use of the Services.
          </Text>
          <Text style={styles.content}>PROMOTIONAL CODES.</Text>
          <Text style={styles.content}>
            Tport may, in Tport’s sole discretion, create promotional codes that
            may be redeemed for Account credit, or other features or benefits
            related to the Services and/or a Third Party Provider’s services,
            subject to any additional terms that Tport establishes on a per
            promotional code basis (“Promo Codes”). You agree that Promo Codes:
            (i) must be used for the intended audience and purpose, and in a
            lawful manner; (ii) may not be duplicated, sold or transferred in
            any manner, or made available to the general public (whether posted
            to a public form or otherwise), unless expressly permitted by Tport;
            (iii) may be disabled by Tport at any time for any reason without
            liability to Tport; (iv) may only be used pursuant to the specific
            terms that Tport establishes for such Promo Code; (v) are not valid
            for cash; and (vi) may expire prior to your use. Tport reserves the
            right to withhold or deduct credits or other features or benefits
            obtained through the use of Promo Codes by you or any other user in
            the event that Tport determines or believes that the use or
            redemption of the Promo Code was in error, fraudulent, illegal, or
            in violation of the applicable Promo Code terms or these Terms.
          </Text>
          <Text style={styles.content}>USER PROVIDED CONTENT.</Text>
          <Text style={styles.content}>
            Tport may, in Tport’s sole discretion, permit you from time to time
            to submit, upload, publish or otherwise make available to Tport
            through the Services textual, audio, and/or visual content and
            information, including commentary and feedback related to the
            Services, initiation of support requests, and submission of entries
            for competitions and promotions (“User Content”). Any User Content
            provided by you remains your property. However, by providing User
            Content to Tport, you grant Tport a worldwide, perpetual,
            irrevocable, transferrable, royalty-free license, with the right to
            sublicense, to use, copy, modify, create derivative works of,
            distribute, publicly display, publicly perform, and otherwise
            exploit in any manner such User Content in all formats and
            distribution channels now known or hereafter devised (including in
            connection with the Services and Tport’s business and on third-party
            sites and services), without further notice to or consent from you,
            and without the requirement of payment to you or any other person or
            entity. You represent and warrant that: (i) you either are the sole
            and exclusive owner of all User Content or you have all rights,
            licenses, consents and releases necessary to grant Tport the license
            to the User Content as set forth above; and (ii) neither the User
            Content nor your submission, uploading, publishing or otherwise
            making available of such User Content nor Tport’s use of the User
            Content as permitted herein will infringe, misappropriate or violate
            a third party’s intellectual property or proprietary rights, or
            rights of publicity or privacy, or result in the violation of any
            applicable law or regulation. You agree to not provide User Content
            that is defamatory, libelous, hateful, violent, obscene,
            pornographic, unlawful, or otherwise offensive, as determined by
            Tport in its sole discretion, whether or not such material may be
            protected by law. Tport may, but shall not be obligated to, review,
            monitor, or remove User Content, at Tport’s sole discretion and at
            any time and for any reason, without notice to you.
          </Text>
          <Text style={styles.content}>NETWORK ACCESS AND DEVICES.</Text>
          <Text style={styles.content}>
            You are responsible for obtaining the data network access necessary
            to use the Services. Your mobile network’s data and messaging rates
            and fees may apply if you access or use the Services from a
            wireless-enabled device and you shall be responsible for such rates
            and fees. You are responsible for acquiring and updating compatible
            hardware or devices necessary to access and use the Services and
            Applications and any updates thereto. Tport does not guarantee that
            the Services, or any portion thereof, will function on any
            particular hardware or devices. In addition, the Services may be
            subject to malfunctions and delays inherent in the use of the
            Internet and electronic communications.
          </Text>
          <Text style={styles.content}>4. Payment</Text>
          <Text style={styles.content}>
            You understand that use of the Services may result in charges to you
            for the services or goods you receive from a Third Party Provider
            (“Charges ”). After you have received services or goods obtained
            through your use of the Service, Tport will facilitate your payment
            of the applicable Charges on behalf of the Third Party Provider as
            such Third Party Provider’s limited payment collection agent.
            Payment of the Charges in such manner shall be considered the same
            as payment made directly by you to the Third Party Provider. Charges
            will be inclusive of applicable taxes where required by law. Tport
            reserves the right to charge you an additional amount for pickup
            facility provided at various places along with applicable taxes
            (including but not limited to GST). Charges paid by you are final
            and non-refundable, unless otherwise determined by Tport. You retain
            the right to request lower Charges from a Third Party Provider for
            services or goods received by you from such Third Party Provider at
            the time you receive such services or goods. Tport will respond
            accordingly to any request from a Third Party Provider to modify the
            Charges for a particular service or good. All Charges are due
            immediately and payment will be facilitated by Tport using the
            preferred payment method designated in your Account, after which
            Tport will send you a receipt by email. If your primary Account
            payment method is determined to be expired, invalid or otherwise not
            able to be charged, you agree that Tport may, as the Third Party
            Provider’s limited payment collection agent, use a secondary payment
            method in your Account, if available. As between you and Tport,
            Tport reserves the right to establish, remove and/or revise Charges
            for any or all services or goods obtained through the use of the
            Services at any time in Tport’s sole discretion. Further, you
            acknowledge and agree that Charges applicable in certain
            geographical areas may increase substantially during times of high
            demand. Tport will use reasonable efforts to inform you of Charges
            that may apply, provided that you will be responsible for Charges
            incurred under your Account regardless of your awareness of such
            Charges or the amounts thereof. Tport may from time to time provide
            certain users with promotional offers, subscriptions and discounts
            that may result in different amounts charged for the same or similar
            services or goods obtained through the use of the Services, and you
            agree that such promotional offers,subscriptions and discounts,
            unless also made available to you, shall have no bearing on your use
            of the Services or the Charges applied to you. You may elect to
            cancel your request for services or goods from a Third Party
            Provider at any time prior to such Third Party Provider’s arrival,
            in which case you may be charged a cancellation fee. This payment
            structure is intended to fully compensate the Third Party Provider
            for the services or goods provided. Except with respect to truck
            transportation services requested through the Application, Tport
            does not designate any portion of your payment as a tip or gratuity
            to the Third Party Provider. Any representation by Tport (on Tport’s
            website, in the Application, or in Tport’s marketing materials) to
            the effect that tipping is “voluntary,” “not required,” and/or
            “included” in the payments you make for services or goods provided
            is not intended to suggest that Tport provides any additional
            amounts, beyond those described above, to the Third Party Provider.
            You understand and agree that, while you are free to provide
            additional payment as a gratuity to any Third Party Provider who
            provides you with services or goods obtained through the Service,
            you are under no obligation to do so. Gratuities are voluntary.
            After you have received services or goods obtained through the
            Service, you will have the opportunity to rate your experience and
            leave additional feedback about your Third Party Provider.
          </Text>
          <Text style={styles.content}>REPAIR OR CLEANING FEES.</Text>
          <Text style={styles.content}>
            You shall be responsible for the cost of repair for damage to, or
            necessary cleaning of, Third Party Provider vehicles and property
            resulting from use of the Services under your Account in excess of
            normal “wear and tear” damages and necessary cleaning (“Repair or
            Cleaning”). In the event that a Third Party Provider reports the
            need for Repair or Cleaning, and such Repair or Cleaning request is
            verified by Tport in Tport’s reasonable discretion, Tport reserves
            the right to facilitate payment for the reasonable cost of such
            Repair or Cleaning on behalf of the Third Party Provider using your
            payment method designated in your Account. Such amounts will be
            transferred by Tport to the applicable Third Party Provider and are
            non-refundable.
          </Text>
          <Text style={styles.content}>
            5. Disclaimers; Limitation of Liability; Indemnity.
          </Text>
          <Text style={styles.content}>DISCLAIMER.</Text>
          <Text style={styles.content}>
            THE SERVICES ARE PROVIDED “AS IS” AND “AS AVAILABLE.” TPORT
            DISCLAIMS ALL REPRESENTATIONS AND WARRANTIES, EXPRESS, IMPLIED OR
            STATUTORY, NOT EXPRESSLY SET OUT IN THESE TERMS, INCLUDING THE
            IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
            PURPOSE AND NON-INFRINGEMENT. IN ADDITION, TPORT MAKES NO
            REPRESENTATION, WARRANTY, OR GUARANTEE REGARDING THE RELIABILITY,
            TIMELINESS, QUALITY, SUITABILITY OR AVAILABILITY OF THE SERVICES OR
            ANY SERVICES OR GOODS REQUESTED THROUGH THE USE OF THE SERVICES, OR
            THAT THE SERVICES WILL BE UNINTERRUPTED OR ERROR-FREE. TPORT DOES
            NOT GUARANTEE THE QUALITY, SUITABILITY, SAFETY OR ABILITY OF THIRD
            PARTY PROVIDERS. YOU AGREE THAT THE ENTIRE RISK ARISING OUT OF YOUR
            USE OF THE SERVICES, AND ANY SERVICE OR GOOD REQUESTED IN CONNECTION
            THEREWITH, REMAINS SOLELY WITH YOU, TO THE MAXIMUM EXTENT PERMITTED
            UNDER APPLICABLE LAW.
          </Text>
          <Text style={styles.content}>LIMITATION OF LIABILITY.</Text>
          <Text style={styles.content}>
            TPORT SHALL NOT BE LIABLE FOR INDIRECT, INCIDENTAL, SPECIAL,
            EXEMPLARY, PUNITIVE OR CONSEQUENTIAL DAMAGES, INCLUDING LOST
            PROFITS, LOST DATA, PERSONAL INJURY OR PROPERTY DAMAGE RELATED TO,
            IN CONNECTION WITH, OR OTHERWISE RESULTING FROM ANY USE OF THE
            SERVICES, EVEN IF TPORT HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH
            DAMAGES. TPORT SHALL NOT BE LIABLE FOR ANY DAMAGES, LIABILITY OR
            LOSSES ARISING OUT OF: (i) YOUR USE OF OR RELIANCE ON THE SERVICES
            OR YOUR INABILITY TO ACCESS OR USE THE SERVICES; OR (ii) ANY
            TRANSACTION OR RELATIONSHIP BETWEEN YOU AND ANY THIRD PARTY
            PROVIDER, EVEN IF TPORT HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH
            DAMAGES. TPORT SHALL NOT BE LIABLE FOR DELAY OR FAILURE IN
            PERFORMANCE RESULTING FROM CAUSES BEYOND TPORT’S REASONABLE CONTROL.
            YOU ACKNOWLEDGE THAT THIRD PARTY TRANSPORTATION PROVIDERS PROVIDING
            TRANSPORTATION SERVICES REQUESTED THROUGH SOME REQUEST BRANDS MAY
            OFFER RIDESHARING OR PEER-TO-PEER TRANSPORTATION SERVICES AND MAY
            NOT BE PROFESSIONALLY LICENSED OR PERMITTED. IN NO EVENT SHALL
            TPORT’S TOTAL LIABILITY TO YOU IN CONNECTION WITH THE SERVICES FOR
            ALL DAMAGES, LOSSES AND CAUSES OF ACTION. TPORT’S SERVICES MAY BE
            USED BY YOU TO REQUEST AND SCHEDULE TRANSPORTATION, GOODS OR
            LOGISTICS SERVICES WITH THIRD PARTY PROVIDERS, BUT YOU AGREE THAT
            TPORT HAS NO RESPONSIBILITY OR LIABILITY TO YOU RELATED TO ANY
            TRANSPORTATION, GOODS OR LOGISTICS SERVICES PROVIDED TO YOU BY THIRD
            PARTY PROVIDERS OTHER THAN AS EXPRESSLY SET FORTH IN THESE TERMS.
            THE LIMITATIONS AND DISCLAIMER IN THIS SECTION 5 DO NOT PURPORT TO
            LIMIT LIABILITY OR ALTER YOUR RIGHTS AS A CONSUMER THAT CANNOT BE
            EXCLUDED UNDER APPLICABLE LAW.
          </Text>
          <Text style={styles.content}>INDEMNITY.</Text>
          <Text style={styles.content}>
            You agree to indemnify and hold Tport and its officers, directors,
            employees and agents harmless from any and all claims, demands,
            losses, liabilities, and expenses (including attorneys’ fees)
            arising out of or in connection with: (i) your use of the Services
            or services or goods obtained through your use of the Services; (ii)
            your breach or violation of any of these Terms; (iii) Tport’s use of
            your User Content; or (iv) your violation of the rights of any third
            party, including Third Party Providers.
          </Text>
          <Text style={styles.content}>6. Governing Law; Arbitration.</Text>
          <Text style={styles.content}>
            Except as otherwise set forth in these Terms, these Terms shall be
            exclusively governed by and construed in accordance with the laws of
            India. Any dispute, conflict, claim or controversy arising out of or
            broadly in connection with or relating to the Services or these
            Terms, including those relating to its validity, its construction or
            its enforceability (any “Dispute”) shall be first mandatorily
            submitted to mediation proceedings in terms of the Indian law. If
            such Dispute has not been settled within sixty (60) days after a
            request for mediation has been submitted under the Indian laws, such
            Dispute can be referred to and shall be exclusively and finally
            resolved by arbitration under the Arbitration and Conciliation Act,
            1996 (“Act”). The Dispute shall be resolved by one (1) arbitrator to
            be appointed in accordance with the Act. The place of both mediation
            and arbitration shall be India. The language of the mediation and/or
            arbitration shall be English, unless you do not speak English, in
            which case the mediation and/or arbitration shall be conducted in
            both English and your native language. The existence and content of
            the mediation and arbitration proceedings, including documents and
            briefs submitted by the parties, any correspondence correspondence
            from the mediator, and correspondence, orders and awards issued by
            the sole arbitrator, shall remain strictly confidential and shall
            not be disclosed to any third party without the express written
            consent from the other party unless: (i) the disclosure to the third
            party is reasonably required in the context of conducting the
            mediation or arbitration proceedings; and (ii) the third party
            agrees unconditionally in writing to be bound by the confidentiality
            obligation stipulated herein.
          </Text>
          <Text style={styles.content}>7. Other Provisions</Text>
          <Text style={styles.content}>CLAIMS OF COPYRIGHT INFRINGEMENT.</Text>
          <Text style={styles.content}>
            Claims of copyright infringement should be sent to Tport’s
            designated agent. Please visit Tport’s web page at
            https://www.tport.in for the designated address and additional
            information. NOTICE. Tport may give notice by means of a general
            notice on the Services, electronic mail to your email address in
            your Account, or by written communication sent to your address as
            set forth in your Account. You may give notice to Tport by written
            communication to Tport's address as mentioned above GENERAL. You may
            not assign or transfer these Terms in whole or in part without
            Tport’s prior written approval. You give your approval to Tport for
            it to assign or transfer these Terms in whole or in part, including
            to: (i) a subsidiary or affiliate; (ii) an acquirer of Tport’s
            equity, business or assets; or (iii) a successor by merger. No joint
            venture, partnership, employment or agency relationship exists
            between you, Tport or any Third Party Provider as a result of the
            contract between you and Tport or use of the Services. If any
            provision of these Terms is held to be illegal, invalid or
            unenforceable, in whole or in part, under any law, such provision or
            part thereof shall to that extent be deemed not to form part of
            these Terms but the legality, validity and enforceability of the
            other provisions in these Terms shall not be affected. In that
            event, the parties shall replace the illegal, invalid or
            unenforceable provision or part thereof with a provision or part
            thereof that is legal, valid and enforceable and that has, to the
            greatest extent possible, a similar effect as the illegal, invalid
            or unenforceable provision or part thereof, given the contents and
            purpose of these Terms. These Terms constitute the entire agreement
            and understanding of the parties with respect to its subject matter
            and replaces and supersedes all prior or contemporaneous agreements
            or undertakings regarding such subject matter. In these Terms, the
            words “including” and “include” mean “including, but not limited
            to.”
          </Text>
          <Text style={styles.content}>
            TPORT GUIDELINES FOR LAW ENFORCEMENT AUTHORITIES
          </Text>
          <Text style={styles.content}>
            The following guidelines are intended to inform law enforcement
            about the legal process for seeking records from Tport. These are
            merely guidelines, and this information may change at any time. For
            private party requests, including requests from civil litigants and
            criminal defendants, we recommend browsing Guidelines for Third
            Party Data Requests.
          </Text>
          <Text style={styles.content}>
            WHAT IS TPORT AND WHAT RECORDS DO WE HAVE?
          </Text>
          <Text style={styles.content}>
            SparshTech is a technology company that has developed an app that
            connects users (Carriers) with driver partners who provide
            transportation to the user. Tport is not a transportation carrier,
            and does not employ any drivers. Users can use the Tport App to
            request transportation via their smartphone, or the web. Tport users
            can choose from a variety of drivers available in his or her
            location. At the end of the ride, both the driver partner and user
            receive a copy of the fare receipt. More information about our
            services is available here. We store and maintain information as
            described in our Privacy Statements and our Terms of Use.
          </Text>
          <Text style={styles.content}>
            WHAT TYPE OF LEGAL PROCESS DOES TPORT REQUIRE BEFORE PRODUCING USER
            OR PARTNER INFORMATION?
          </Text>
          <Text style={styles.content}>
            For India Law Enforcement We require valid and sufficient legal
            process before we can disclose business records regarding partners,
            users, or transports. In most instances, we won’t be able to provide
            any information without a valid subpoena, court order, or search
            warrant. We accept law enforcement requests via email to
            info@sparshtech.com or via personal service through our corporate
            agent, National Registered Agents, SPARSH Technologies, RAJAT SANKUL
            Opp. S.T. Stand,Ganeshpeth Colony, Nagpur, Maharashtra. Our
            acceptance of legal process does not waive any legal objections
            Tport may have and may raise in response to the request.
          </Text>
          <Text style={styles.content}>
            For India Law Enforcement: We disclose business records only in
            accordance with our terms of service and applicable law. A valid
            India court order (via mutual legal assistance treaty, mutual legal
            assistance agreement, or letter rogatory) may be required to compel
            disclosure of certain records. We accept non-India requests via
            email to info@sparshtech.com or via personal service to the
            following address:SPARSH Technologies, RAJAT SANKUL Opp. S.T.
            Stand,Ganeshpeth Colony, Nagpur, Maharashtra.Our acceptance of legal
            process does not waive any legal objections Tport B.V. may have and
            may raise in response to the request.
          </Text>
          <Text style={styles.content}>
            WHAT FORM OF REQUESTS DOES TPORT REQUIRE, AND HOW ARE REQUESTS
            PROCESSED? To respond to a request, we will need to receive the
            applicable process described above, as well as a valid return email
            address from an official government domain. We review each request
            for facial and substantive validity, and will reject requests that
            are not facially and substantively valid. Among other things, we
            require requests to be narrowly tailored to a legitimate law
            enforcement need and will reject overly broad, vague, or unduly
            burdensome requests. In order to make sure your Law Enforcement
            Request is valid and does not seek more information than necessary,
            we ask for the following: A sufficiently narrow/defined time period;
            A specific event or action that the subject took; A specific
            reference (i.e., you must uniquely identify a user or Transporter
            partner) We disclose data to law enforcement when we determine that
            we are required to do so by law. In those instances, we will search
            for and disclose data that we are reasonably able to locate and
            retrieve.
          </Text>
          <Text style={styles.content}>
            HOW DOES TPORT HANDLE EMERGENCY REQUESTS?
          </Text>
          <Text style={styles.content}>
            We have a process for evaluating requests on an emergency basis
            where there is an emergency that involves protecting a user, driver
            partner, or third party or stopping illegal activity that poses an
            immediate threat of death or serious bodily harm. Requestors must
            submit an Emergency Request Form (which can be requested through
            info@sparshtech.com) that describes in detail the nature of the
            emergency, and we review these requests on a case-by-case basis. Law
            enforcement can submit an emergency request by emailing
            info@sparshtech.com. Please note that we will only review and
            respond to emergency requests from law enforcement, and will not
            respond to emergency requests sent to this address by non-law
            enforcement officials. Non-law enforcement officials aware of an
            emergency situation should immediately and directly contact local
            law enforcement officials.
          </Text>
          <Text style={styles.content}>
            DOES TPORT NOTIFY INDIVIDUALS OF A LAW ENFORCEMENT REQUEST FOR
            INFORMATION RELATING TO THEM?
          </Text>
          <Text style={styles.content}>
            Yes, we may notify subjects before producing their information to
            law enforcement, unless we are prohibited by law from doing so, or
            in exceptional circumstances such as emergencies. Law enforcement
            officials who believe that notification would jeopardize an
            investigation should obtain an appropriate court order or other
            appropriate process establishing that notice is prohibited.
          </Text>
          <Text style={styles.content}>
            DOES TPORT PROVIDE A CERTIFICATE OF AUTHENTICATION OR EXPERT
            TESTIMONY?
          </Text>
          <Text style={styles.content}>
            We may provide a certification from our records custodian but are
            not generally able to provide in-person or expert witness testimony.
            Law enforcement officials with questions about these guidelines
            should email info@sparshtech.com. Please note that we will not
            respond to non-law enforcement inquiries received at this email
            address. For non-law enforcement inquiries, please see Guidelines
            for Third Party Data Requests.
          </Text>
        </ScrollView>
      </View>
    </BackgroundImage>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: "column",
    alignItems: "center",
    width: window.width,
    backgroundColor: "black",
    opacity: 0.8,
    paddingHorizontal: 10,
    fontFamily: "open-sans",
  },

  heading: {
    fontSize: 20,
    color: "white",
    textAlign: "center",
    margin: 10,
    fontFamily: "open-sans",
  },
  content: { fontFamily: "open-sans", color: "white", margin: 5 },
  subContent: {
    fontFamily: "open-sans",
    color: "white",
    // margin: 5,
    paddingLeft: 25,
  },
});

export default TAndCModalScreen;
